import styles from './labels.module.scss';
import { LabelItem } from '../../../../../types/interface.ts';

export const labels: LabelItem[] = [
  { text: 'Q умягченной воды после Ф4/1,2,3', className: styles['rashod-vody-filtr-text'] },
  { text: 'Q воды в канализацию', className: styles['rashod-kanalizacia-text'] },
  { text: 'P воды после Ф4/1,2,3', className: styles['davlenie-posle-filtrov-text'] },
  { text: 'ИМ2', className: styles['im2-text'] },
  { text: 'Ф3/1', className: styles['f3-1-text'] },
  { text: 'Ф3/2', className: styles['f3-2-text'] },
  { text: 'Ф3/3', className: styles['f3-3-text'] },
  { text: 'Ф3/4', className: styles['f3-4-text'] },
  { text: 'Ф3/5', className: styles['f3-5-text'] },
  { text: 'Ф3/6', className: styles['f3-6-text'] },
  { text: 'Ф3/7', className: styles['f3-7-text'] },
  { text: 'Ф4/1', className: styles['f4-1-text'] },
  { text: 'Ф4/2', className: styles['f4-2-text'] },
  { text: 'Ф4/3', className: styles['f4-3-text'] },
  { text: 'Е2/1', className: styles['e2-1-text'] },
  { text: 'Е2/2', className: styles['e2-2-text'] },
  { text: 'H4/1', className: styles['n4-1-text'] },
  { text: 'H4/2', className: styles['n4-2-text'] },
  { text: 'H5/1', className: styles['n5-1-text'] },
  { text: 'H5/2', className: styles['n5-2-text'] },
  { text: 'H6/1', className: styles['n6-1-text'] },
  { text: 'H6/2', className: styles['n6-2-text'] },
  { text: 'H6/3', className: styles['n6-3-text'] },
  { text: 'T в E2/1 север', className: styles['temper-e2-1-sever-text'] },
  { text: 'T в E2/1 юг', className: styles['temper-e2-1-ug-text'] },
  { text: 'T в E2/2 север', className: styles['temper-e2-2-sever-text'] },
  { text: 'T в E2/2 юг', className: styles['temper-e2-2-ug-text'] },
  { text: 'H воды (Титан)', className: styles['uroven-titan-e2-1-text'] },
  { text: 'H воды (Мида)', className: styles['uroven-mida-e2-1-text'] },
  { text: 'H воды (Титан)', className: styles['uroven-titan-e2-2-text'] },
  { text: 'H воды (Мида)', className: styles['uroven-mida-e2-2-text'] },
  { text: 'P воды на карбон', className: styles['carbon-text'] },
  { text: 'P воды на к.265', className: styles['k265-text'] },
  { text: 'P воды на к.312', className: styles['k312-text'] },
  { text: 'Из помещения №1', className: styles['pomeshenie-text'] },
  { text: 'В канализацию', className: styles['kanalizacia-text'] },
];

